AWSTemplateFormatVersion: "2010-09-09"
Description: "Backup Plan template by Kishan Khatrani"
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  RuleForDailyBackupsRetention:
    Description: Please enter DailyBackups for this Backup Plan
    Type: String
    Default: 7

  RuleForWeeklyBackupsRetention:
    Description: Please enter WeeklyBackups for this Backup Plan
    Type: String
    Default: 28
    
  RuleForMonthlyBackupsRetention:
    Description: Please enter MonthlyBackups for this Backup Plan
    Type: String
    Default: 28
    
  ResourceKey:
    Description: Please enter ResourceKey for this Backup Plan
    Type: String
    Default: backup
    
  ResourceKeyValue:
    Description: Please enter ResourceKeyValue for this Backup Plan
    Type: String
    Default: true
    
Resources:
  BackupVaultBackups:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "BackupVaultBackups"

  BackupPlanBackups:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: "BackupPlanBackups"
        BackupPlanRule:
          -
            RuleName: "RuleForDailyBackups"
            TargetBackupVault: !Ref BackupVaultBackups
            ScheduleExpression: "cron(0 5 ? * * *)"
            Lifecycle:
              DeleteAfterDays: !Ref RuleForDailyBackupsRetention
          -
            RuleName: "RuleForWeeklyBackups"
            TargetBackupVault: !Ref BackupVaultBackups
            ScheduleExpression: "cron(0 5 ? * 1 *)"
            Lifecycle:
              DeleteAfterDays: !Ref RuleForWeeklyBackupsRetention
          -
            RuleName: "RuleForMonthlyBackups"
            TargetBackupVault: !Ref BackupVaultBackups
            ScheduleExpression: "cron(0 5 1 * ? *)"
            Lifecycle:
              DeleteAfterDays: !Ref RuleForMonthlyBackupsRetention
    DependsOn: BackupVaultBackups

  TagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole"
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: !Ref ResourceKey
           ConditionValue: !Ref ResourceKeyValue
      BackupPlanId: !Ref BackupPlanBackups
    DependsOn: BackupPlanBackups
